### ISSUE TITLE
"test-runner" is inaccurate

### ISSUE THREAD

**Issue by eliasmalik** [foundersandcoders/Node-Shell-Workshop#15]
In the project, the thing they are being asked to build is described as a test-runner. It's actually a TAP output formatter. `tape` is still the thing actually running the tests.

I would suggest that we replace references to 'test-runner' with "TAP output formatter", or alternatively "test output formatter" if you don't feel like explaining what TAP is (which would be fair enough).

**Comment by bradreeder** [comment]
Hey @eliascodes , thanks for raising this. I'm happy with the change if you're free to make a PR? Let me know otherwise and will try to get to it before week 5.
