### ISSUE TITLE
update hint for lesson-1 grep task

### ISSUE THREAD

**Issue by bradreeder** [foundersandcoders/Node-Shell-Workshop#19]
```Hint: try doing this just with fs first and see what happens. You're going to need a specific core module in order to access the whole line of a file as you're reading it.```

I remember when I delivered this that someone solved the task without using the module referenced here. I will update this hint to the point to the existence of this module rather than imply it's necessary.

**Comment by joeylouise** [comment]
@bradreeder, I agree, when I did it I used a different module and I forgot to raise an issue about it!
